#!/bin/bash

javac -cp src/main/java src/main/java/com/blitzhetz/*.java

if [ $? -eq 0 ]; then
    echo "Compilation successful."

    java -cp src/main/java com.blitzhetz.Main
else
    echo "Compilation failed, what is wrong with you bruhh"
fi
